FROM node:14.16.0-alpine3.10 as build
WORKDIR /app
COPY /frontend/package*.json ./
RUN npm ci
COPY ./frontend ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]