FROM openjdk:11-jdk
RUN addgroup -system spring
RUN useradd -G spring user
ARG DEPENDENCY=/backend/target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
EXPOSE 8080
ENTRYPOINT ["java","-cp","app:app/lib/*","wyu17.backend.DegreePlannerBackendApplication"]